name: Generate LiaScript PDFs with liaex

on:
  push:
    branches:
      - master
      - pdf_export
  workflow_dispatch:

jobs:
  build_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install LiaScript Exporter (liaex)
        run: npm install -g @liascript/exporter

      - name: Create PDF output directory
        run: mkdir pdf_output

      - name: Convert Markdown to PDF with Commit Date Prefix using liaex
        run: |
          find . -maxdepth 1 -name "*.md" -print0 | while IFS= read -r -d $'\0' file; do
            filename="${file#./}"
            echo "Processing: $filename"

            # JJJJ-MM-TT des letzten Commits für die Datei ermitteln
            commit_date=$(git log -1 --pretty="format:%as" -- "$filename")
            if [ -z "$commit_date" ]; then
              commit_date=$(date +%Y-%m-%d) # Fallback: heutiges Datum
            fi

            base_name="${filename%.md}"
            pdf_name="${commit_date}_${base_name}.pdf"
            output_path="pdf_output/$pdf_name"

            echo "Output PDF: $output_path"

            # Konvertierung mit liaex, Format pdf, erhöhtes Timeout
            # Füge hier bei Bedarf weitere --pdf-* Optionen hinzu (z.B. --pdf-theme)
            liaex --input "$filename" --format pdf --output "$output_path" --pdf-timeout 60000

            if [ $? -ne 0 ]; then
              echo "Error converting $filename to PDF using liaex."
              # exit 1 # Optional: Workflow bei Fehler abbrechen
            fi
          done

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liascript-pdfs
          path: pdf_output/
          if-no-files-found: warn
